#include <cstdlib>
#include <iostream>
#include "core/GameEngine.h"
using namespace sanguosha;
namespace {
std::shared_ptr<Card> equipment(const CardId& id, const std::string& name, CardType type, EquipmentSlot slot){return std::make_shared<Card>(id,name,type,Suit::Spade,2,EquipmentData{slot,2});}
std::shared_ptr<Card> vine(){return equipment("vine", "藤甲", CardType::Armor, EquipmentSlot::Armor);}
std::shared_ptr<Card> otherWeapon(){return equipment("other-weapon", "other-weapon", CardType::Weapon, EquipmentSlot::Weapon);}
[[noreturn]] void fail(const char* m){std::cerr<<"FAIL: "<<m<<'\n';std::exit(1);} void ok(bool v,const char*m){if(!v)fail(m);}
std::shared_ptr<Card> weapon(){return std::make_shared<Card>("ice","\xE5\xAF\x92\xE5\x86\xB0\xE5\x89\x91",CardType::Weapon,Suit::Spade,2,EquipmentData{EquipmentSlot::Weapon,2});}
GameEngine setup(){GameEngine x;x.createGame({"A","B"});x.startGame();for(auto&p:x.players()){std::vector<CardId> ids;for(auto&c:p->handCards())ids.push_back(c->id());for(auto&i:ids)p->removeCard(i);}x.testingEquip(1,weapon());x.players()[1]->addCard(std::make_shared<Card>("target-card","target",CardType::Peach,Suit::Heart,1));return x;}
GameEngine setupThree(){GameEngine x;x.createGame({"A","B","C"});x.startGame();for(auto&p:x.players()){std::vector<CardId> ids;for(auto&c:p->handCards())ids.push_back(c->id());for(auto&i:ids)p->removeCard(i);}x.testingEquip(1,weapon());x.players()[1]->addCard(std::make_shared<Card>("target-a","target-a",CardType::Peach,Suit::Heart,1));x.players()[1]->addCard(std::make_shared<Card>("target-a2","target-a2",CardType::Dodge,Suit::Club,2));x.players()[2]->addCard(std::make_shared<Card>("target-b","target-b",CardType::Peach,Suit::Heart,1));return x;}
void hit(GameEngine& x,DamageNature nature=DamageNature::Normal){x.testingStartSlash(1,{2},1,nature);auto r=*x.pendingResponse();ok(x.submitAction(RespondAction{2,r.requestId,std::nullopt}).accepted,"Dodge pass");}
std::uint64_t activate(GameEngine& x){hit(x);auto id=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,id,{"ice-sword-activate"}}).accepted,"activate");return x.pendingCardSelection()->requestId;}
void iceSwordTriggersBeforeSlashDamage(){auto x=setup();hit(x);const auto& c=x.iceSwordContext();const auto& r=x.pendingCardSelection();const auto& d=x.testingDeferredSlashDamage();ok(x.player(2)->hp()==4&&c&&c->source==1&&c->target==2&&r&&r->purpose==CardSelectionPurpose::IceSwordPrompt&&r->requester==1&&d&&d->source==1&&d->target==2&&d->damageAmount==1&&d->damageNature==DamageNature::Normal,"Ice Sword pauses damage before HP loss");}
void iceSwordPassContinuesOriginalDamage(){auto x=setup();hit(x);const auto id=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,id,{}}).accepted,"Ice Sword Pass");ok(x.player(2)->hp()==3&&!x.iceSwordContext()&&!x.pendingCardSelection()&&!x.testingDeferredSlashDamage()&&!x.pendingResponse(),"Pass resumes exactly one original damage");}
void iceSwordPreventsDamageWhenActivated(){auto x=setup();hit(x);const auto id=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,id,{"ice-sword-activate"}}).accepted,"Ice Sword Activate");ok(x.player(2)->hp()==4&&x.iceSwordContext()&&x.iceSwordContext()->activated&&x.pendingCardSelection()&&x.pendingCardSelection()->purpose==CardSelectionPurpose::IceSwordDiscard&&!x.testingDeferredSlashDamage()&&!x.pendingResponse(),"activation prevents damage and starts discard stage");}
void iceSwordPreventedDamageCannotResume(){auto x=setup();hit(x);const auto id=x.pendingCardSelection()->requestId;x.submitAction(SelectCardsAction{1,id,{"ice-sword-activate"}});ok(!x.submitAction(SelectCardsAction{1,id,{}}).accepted&&x.player(2)->hp()==4&&!x.testingDeferredSlashDamage(),"old prompt cannot resume prevented damage");}
void iceSwordStartsDiscardAfterActivation(){auto x=setup();activate(x);auto r=*x.pendingCardSelection();ok(x.player(2)->hp()==4&&r.purpose==CardSelectionPurpose::IceSwordDiscard&&r.requester==1&&r.target==2&&r.minCount==1&&r.maxCount==1&&x.iceSwordContext()->activated,"discard request starts");}
void iceSwordDiscardsTwoCards(){auto x=setup();x.testingEquip(2,std::make_shared<Card>("armor","armor",CardType::Armor,Suit::Club,1,EquipmentData{EquipmentSlot::Armor,0}));auto a=activate(x);ok(x.submitAction(SelectCardsAction{1,a,{"target-card"}}).accepted,"discard hand");auto b=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,b,{"armor"}}).accepted,"discard armor");ok(!x.player(2)->equipment(EquipmentSlot::Armor)&&x.player(2)->handCards().empty()&&!x.pendingCardSelection()&&!x.iceSwordContext()&&x.player(2)->hp()==4,"two discarded and cleanup");}
void iceSwordDiscardsAllWhenOnlyOneCardExists(){auto x=setup();auto a=activate(x);ok(x.submitAction(SelectCardsAction{1,a,{"target-card"}}).accepted&&!x.pendingCardSelection()&&!x.iceSwordContext()&&x.player(2)->hp()==4,"one card ends discard");}
void iceSwordRecalculatesCandidatesForSecondDiscard(){auto x=setup();x.players()[1]->addCard(std::make_shared<Card>("other","other",CardType::Dodge,Suit::Club,1));auto a=activate(x);ok(x.submitAction(SelectCardsAction{1,a,{"target-card"}}).accepted,"first discard");auto r=*x.pendingCardSelection();ok(r.requestId!=a&&r.selectableCards.size()==1&&r.selectableCards[0].cardId=="other","second candidates recalculated");}
void iceSwordRejectsIllegalDiscardCandidate(){auto x=setup();x.players()[0]->addCard(std::make_shared<Card>("own","own",CardType::Peach,Suit::Club,1));auto a=activate(x);ok(!x.submitAction(SelectCardsAction{1,a,{"own"}}).accepted&&x.pendingCardSelection()&&x.iceSwordContext()->discardsRemaining==2&&x.player(2)->handCards().size()==1,"illegal discard rejected");}
void iceSwordRejectsStaleDiscardRequest(){auto x=setup();x.players()[1]->addCard(std::make_shared<Card>("other","other",CardType::Dodge,Suit::Club,1));auto a=activate(x);x.submitAction(SelectCardsAction{1,a,{"target-card"}});auto b=x.pendingCardSelection()->requestId;ok(!x.submitAction(SelectCardsAction{1,a,{"target-card"}}).accepted&&x.pendingCardSelection()->requestId==b&&x.player(2)->handCards().size()==1,"stale discard rejected");}
void iceSwordPassPreservesFireSlashDamage(){auto x=setup();x.testingEquip(2,vine());hit(x,DamageNature::Fire);ok(x.testingDeferredSlashDamage()->damageNature==DamageNature::Fire,"Fire snapshot retained");auto id=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,id,{}}).accepted&&x.player(2)->hp()==2&&!x.iceSwordContext(),"Fire Pass uses original Fire damage and Vine modifier once");}
void iceSwordPassPreservesThunderSlashDamage(){auto x=setup();x.testingEquip(2,vine());hit(x,DamageNature::Thunder);ok(x.testingDeferredSlashDamage()->damageNature==DamageNature::Thunder,"Thunder snapshot retained");auto id=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,id,{}}).accepted&&x.player(2)->hp()==3&&!x.iceSwordContext(),"Thunder Pass uses original Thunder damage once");}
void iceSwordPreventsFireSlashDamage(){auto x=setup();hit(x,DamageNature::Fire);auto id=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,id,{"ice-sword-activate"}}).accepted&&x.player(2)->hp()==4&&!x.testingDeferredSlashDamage()&&x.pendingCardSelection()->purpose==CardSelectionPurpose::IceSwordDiscard,"Activate prevents Fire damage");}
void iceSwordPreventsThunderSlashDamage(){auto x=setup();hit(x,DamageNature::Thunder);auto id=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,id,{"ice-sword-activate"}}).accepted&&x.player(2)->hp()==4&&!x.testingDeferredSlashDamage()&&x.pendingCardSelection()->purpose==CardSelectionPurpose::IceSwordDiscard,"Activate prevents Thunder damage");}
void iceSwordMultiTargetContinuesAfterFirstTarget(){auto x=setupThree();x.testingStartSlash(1,{2,3});auto first=*x.pendingResponse();ok(x.submitAction(RespondAction{2,first.requestId,std::nullopt}).accepted,"first Dodge pass");auto prompt=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,prompt,{"ice-sword-activate"}}).accepted,"activate on first target");auto one=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,one,{"target-a"}}).accepted,"discard first card");auto two=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,two,{"target-a2"}}).accepted,"discard second card");auto next=x.pendingResponse();ok(x.player(2)->hp()==4&&!x.iceSwordContext()&&next&&next->type==ResponseType::Dodge&&next->responder==3,"Ice Sword completion advances to second target");}
void iceSwordMultiTargetUsesIndependentContexts(){auto x=setupThree();x.testingStartSlash(1,{2,3});auto first=*x.pendingResponse();x.submitAction(RespondAction{2,first.requestId,std::nullopt});auto firstPrompt=x.pendingCardSelection()->requestId;ok(x.submitAction(SelectCardsAction{1,firstPrompt,{}}).accepted&&x.player(2)->hp()==3,"first target Pass receives damage");auto second=*x.pendingResponse();ok(second.responder==3,"second target response created");x.submitAction(RespondAction{3,second.requestId,std::nullopt});auto context=*x.iceSwordContext();auto secondPrompt=x.pendingCardSelection()->requestId;ok(context.target==3&&secondPrompt!=firstPrompt&&context.snapshot.target==3,"second target owns independent Ice context");ok(x.submitAction(SelectCardsAction{1,secondPrompt,{"ice-sword-activate"}}).accepted&&x.player(3)->hp()==4,"second target activation prevents only its damage");}
void iceSwordPromptTimeoutActsAsPass(){auto x=setup();hit(x);ok(x.handleTimeout().accepted&&x.player(2)->hp()==3&&!x.iceSwordContext()&&!x.pendingCardSelection()&&!x.testingDeferredSlashDamage(),"Ice Sword prompt timeout declines exactly once");const auto hp=x.player(2)->hp();x.handleTimeout();ok(x.player(2)->hp()==hp&&!x.iceSwordContext()&&!x.pendingCardSelection()&&!x.testingDeferredSlashDamage(),"completed Ice Sword timeout cannot run twice");}
void iceSwordDiscardTimeoutUsesLegalSelection(){auto x=setup();x.players()[1]->addCard(std::make_shared<Card>("other","other",CardType::Dodge,Suit::Club,1));activate(x);ok(x.handleTimeout().accepted&&x.pendingCardSelection()&&x.pendingCardSelection()->purpose==CardSelectionPurpose::IceSwordDiscard,"first discard timeout chooses a legal candidate");ok(x.handleTimeout().accepted&&x.player(2)->handCards().empty()&&!x.pendingCardSelection()&&!x.iceSwordContext()&&x.player(2)->hp()==4,"second discard timeout completes without damage");}
void iceSwordDoesNotTriggerAfterUnequip(){auto x=setup();x.testingRemoveEquipment(1,EquipmentSlot::Weapon);hit(x);ok(x.player(2)->hp()==3&&!x.iceSwordContext()&&!x.pendingCardSelection(),"unequipped Ice Sword does not prompt and normal damage resolves");}
void iceSwordDoesNotTriggerAfterReplacement(){auto x=setup();x.testingEquip(1,otherWeapon());hit(x);ok(x.player(1)->equipment(EquipmentSlot::Weapon)->id()=="other-weapon"&&x.player(2)->hp()==3&&!x.iceSwordContext()&&!x.pendingCardSelection(),"replaced Ice Sword does not prompt and normal damage resolves");}
void iceSwordPendingPromptInvalidatesWhenWeaponIsLost(){auto x=setup();hit(x);auto old=x.pendingCardSelection()->requestId;x.testingRemoveEquipment(1,EquipmentSlot::Weapon);ok(!x.submitAction(SelectCardsAction{1,old,{"ice-sword-activate"}}).accepted&&x.player(2)->hp()==3&&!x.iceSwordContext()&&!x.pendingCardSelection()&&!x.testingDeferredSlashDamage(),"weapon loss invalidates prompt and resumes original damage once");}
void iceSwordDiscardContinuesAfterWeaponIsLost(){auto x=setup();auto request=activate(x);x.testingRemoveEquipment(1,EquipmentSlot::Weapon);ok(x.iceSwordContext()&&x.iceSwordContext()->activated&&x.pendingCardSelection()->requestId==request,"activated Ice Sword remains locked after weapon loss");ok(x.submitAction(SelectCardsAction{1,request,{"target-card"}}).accepted&&x.player(2)->hp()==4&&!x.iceSwordContext()&&!x.pendingCardSelection(),"locked discard completes without resuming damage");}
void iceSwordClearsWhenAttackerDies(){auto x=setupThree();x.testingStartSlash(1,{2});auto dodge=*x.pendingResponse();x.submitAction(RespondAction{2,dodge.requestId,std::nullopt});auto old=x.pendingCardSelection()->requestId;x.testingKillPlayer(1);ok(!x.submitAction(SelectCardsAction{1,old,{"ice-sword-activate"}}).accepted&&!x.iceSwordContext()&&!x.pendingCardSelection()&&!x.testingDeferredSlashDamage(),"attacker death clears pending Ice Sword interaction");x.handleTimeout();ok(!x.iceSwordContext()&&!x.pendingCardSelection(),"attacker death timeout cannot revive Ice Sword interaction");}
void iceSwordClearsWhenTargetDies(){auto x=setupThree();x.testingStartSlash(1,{2});auto dodge=*x.pendingResponse();x.submitAction(RespondAction{2,dodge.requestId,std::nullopt});auto old=x.pendingCardSelection()->requestId;x.testingKillPlayer(2);ok(!x.submitAction(SelectCardsAction{1,old,{"ice-sword-activate"}}).accepted&&!x.iceSwordContext()&&!x.pendingCardSelection()&&!x.testingDeferredSlashDamage(),"target death clears pending Ice Sword interaction");x.handleTimeout();ok(!x.iceSwordContext()&&!x.pendingCardSelection(),"target death timeout cannot revive Ice Sword interaction");}
void iceSwordClearsOnGameOver(){auto x=setup();hit(x);auto old=x.pendingCardSelection()->requestId;x.testingKillPlayer(2);ok(x.gameOver()&&!x.iceSwordContext()&&!x.pendingCardSelection()&&!x.testingDeferredSlashDamage()&&!x.submitAction(SelectCardsAction{1,old,{"ice-sword-activate"}}).accepted,"GameOver clears Ice Sword and rejects stale action");ok(!x.handleTimeout().accepted,"GameOver timeout cannot resume Ice Sword");}
void iceSwordContextDoesNotLeakAfterLifecycleCleanup(){auto x=setup();hit(x);auto old=x.pendingCardSelection()->requestId;x.testingRemoveEquipment(1,EquipmentSlot::Weapon);x.testingEquip(1,weapon());x.testingStartSlash(1,{2});auto dodge=*x.pendingResponse();x.submitAction(RespondAction{2,dodge.requestId,std::nullopt});auto fresh=*x.iceSwordContext();ok(fresh.requestId!=old&&fresh.target==2&&!fresh.activated&&fresh.discardsRemaining==0&&x.testingDeferredSlashDamage()&&x.testingDeferredSlashDamage()->target==2,"next Slash creates a fresh Ice Sword context after lifecycle cleanup");}
}
int main(){iceSwordTriggersBeforeSlashDamage();iceSwordPassContinuesOriginalDamage();iceSwordPreventsDamageWhenActivated();iceSwordPreventedDamageCannotResume();iceSwordStartsDiscardAfterActivation();iceSwordDiscardsTwoCards();iceSwordDiscardsAllWhenOnlyOneCardExists();iceSwordRecalculatesCandidatesForSecondDiscard();iceSwordRejectsIllegalDiscardCandidate();iceSwordRejectsStaleDiscardRequest();iceSwordPassPreservesFireSlashDamage();iceSwordPassPreservesThunderSlashDamage();iceSwordPreventsFireSlashDamage();iceSwordPreventsThunderSlashDamage();iceSwordMultiTargetContinuesAfterFirstTarget();iceSwordMultiTargetUsesIndependentContexts();iceSwordPromptTimeoutActsAsPass();iceSwordDiscardTimeoutUsesLegalSelection();iceSwordDoesNotTriggerAfterUnequip();iceSwordDoesNotTriggerAfterReplacement();iceSwordPendingPromptInvalidatesWhenWeaponIsLost();iceSwordDiscardContinuesAfterWeaponIsLost();iceSwordClearsWhenAttackerDies();iceSwordClearsWhenTargetDies();iceSwordClearsOnGameOver();iceSwordContextDoesNotLeakAfterLifecycleCleanup();std::cout<<"BasicSanguoshaIceSwordTests PASS\n";}
