#include <cstdlib>
#include <iostream>
#include <memory>
#include <vector>
#include "cards/Card.h"
#include "core/GameEngine.h"
using namespace sanguosha;
namespace { [[noreturn]] void fail(const char* m){std::cerr<<"FAIL: "<<m<<'\n';std::exit(1);} void ok(bool v,const char*m){if(!v)fail(m);} std::shared_ptr<Card> eq(const char*i,const char*n,EquipmentSlot s){auto t=s==EquipmentSlot::Weapon?CardType::Weapon:s==EquipmentSlot::Armor?CardType::Armor:s==EquipmentSlot::OffensiveHorse?CardType::OffensiveHorse:CardType::DefensiveHorse;return std::make_shared<Card>(i,n,t,Suit::Spade,1,EquipmentData{s,3});} void clear(const std::shared_ptr<Player>&p){std::vector<CardId>x;for(auto&c:p->handCards())x.push_back(c->id());for(auto&i:x)p->removeCard(i);} GameEngine g(bool bow=true){GameEngine x;x.createGame({"A","B"});x.startGame();for(auto&p:x.players())clear(p);if(bow)x.testingEquip(1,eq("bow","麒麟弓",EquipmentSlot::Weapon));return x;} void hit(GameEngine&x,DamageNature n=DamageNature::Normal){x.testingStartSlash(1,{2},1,n);auto r=x.pendingResponse();ok(r.has_value(),"dodge request");ok(x.submitAction(RespondAction{2,r->requestId,std::nullopt}).accepted,"hit pass");} void test(){auto x=g();x.testingEquip(2,eq("off","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=x.pendingCardSelection();ok(s&&s->purpose==CardSelectionPurpose::KirinBowMount&&s->selectableCards.size()==1,"direct slash requests +1 mount");ok(x.submitAction(SelectCardsAction{1,s->requestId,{"off"}}).accepted,"select mount");ok(!x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"mount removed"); auto y=g();y.testingEquip(2,eq("def","绝影",EquipmentSlot::DefensiveHorse));hit(y,DamageNature::Fire);auto q=y.pendingCardSelection();ok(q&&q->selectableCards[0].cardId=="def","fire triggers -1 mount");ok(y.handleTimeout().accepted&&y.player(2)->equipment(EquipmentSlot::DefensiveHorse),"timeout pass"); auto z=g(false);z.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(z);ok(!z.pendingCardSelection(),"no bow no request"); }
void kirinBowDoesNotTriggerWhenSlashIsDodged(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));x.testingStartSlash(1,{2});auto r=*x.pendingResponse();x.players()[1]->addCard(std::make_shared<Card>("d","闪",CardType::Dodge,Suit::Heart,2));ok(x.submitAction(RespondAction{2,r.requestId,"d"}).accepted,"dodge accepted");ok(x.player(2)->hp()==4&&!x.pendingCardSelection()&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"dodged slash has no Kirin request");}
void kirinBowDoesNotTriggerWhenSlashIsPreventedByVine(){auto x=g();x.testingEquip(2,eq("vine","藤甲",EquipmentSlot::Armor));x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));x.testingStartSlash(1,{2});ok(x.player(2)->hp()==4&&!x.pendingCardSelection()&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"Vine immunity has no Kirin request");}
void kirinBowOffersBothMountsOnly(){auto x=g();x.testingEquip(2,eq("off","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(2,eq("def","绝影",EquipmentSlot::DefensiveHorse));x.testingEquip(2,eq("w","青釭剑",EquipmentSlot::Weapon));x.testingEquip(2,eq("a","白银狮子",EquipmentSlot::Armor));hit(x);auto s=*x.pendingCardSelection();ok(s.selectableCards.size()==2,"both mounts only");ok((s.selectableCards[0].cardId=="off"||s.selectableCards[1].cardId=="off")&&(s.selectableCards[0].cardId=="def"||s.selectableCards[1].cardId=="def"),"both mount ids present");}
void kirinBowRejectsWeaponCandidate(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(2,eq("w","青釭剑",EquipmentSlot::Weapon));hit(x);auto s=*x.pendingCardSelection();ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"w"}}).accepted,"weapon candidate rejected");ok(x.player(2)->equipment(EquipmentSlot::Weapon)&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse)&&x.pendingCardSelection(),"invalid candidate changes nothing");}
void kirinBowRejectsStaleRequest(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=*x.pendingCardSelection();ok(x.submitAction(SelectCardsAction{1,s.requestId,{}}).accepted,"pass accepted");ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"m"}}).accepted,"stale request rejected");ok(x.player(2)->equipment(EquipmentSlot::OffensiveHorse)&&!x.kirinBowContext(),"stale request changes nothing");}
GameEngine g3(){GameEngine x;x.createGame({"A","B","C"});x.startGame();for(auto&p:x.players())clear(p);x.testingEquip(1,eq("bow","麒麟弓",EquipmentSlot::Weapon));return x;} void hit3(GameEngine&x){x.testingStartSlash(1,{2});auto r=*x.pendingResponse();ok(x.submitAction(RespondAction{2,r.requestId,std::nullopt}).accepted,"hit3");}
void kirinBowRejectsNonActor(){auto x=g3();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit3(x);auto s=*x.pendingCardSelection();ok(!x.submitAction(SelectCardsAction{3,s.requestId,{"m"}}).accepted,"non actor rejected");ok(x.pendingCardSelection()&&x.kirinBowContext()->source==1&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"non actor unchanged");}
void kirinBowRejectsArmorCandidate(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(2,eq("a","白银狮子",EquipmentSlot::Armor));hit(x);auto s=*x.pendingCardSelection();ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"a"}}).accepted,"armor rejected");ok(x.pendingCardSelection()&&x.player(2)->equipment(EquipmentSlot::Armor)&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"armor unchanged");}
void kirinBowRejectsUnknownCandidate(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=*x.pendingCardSelection();ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"unknown"}}).accepted,"unknown rejected");ok(x.pendingCardSelection()&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"unknown unchanged");}
void kirinBowRejectsOtherPlayersMount(){auto x=g3();x.testingEquip(2,eq("m2","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(3,eq("m3","绝影",EquipmentSlot::DefensiveHorse));hit3(x);auto s=*x.pendingCardSelection();ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"m3"}}).accepted,"other mount rejected");ok(x.player(2)->equipment(EquipmentSlot::OffensiveHorse)&&x.player(3)->equipment(EquipmentSlot::DefensiveHorse)&&x.kirinBowContext()->target==2,"other mount unchanged");}
void kirinBowRejectsCandidateRemovedAfterRequest(){auto x=g();x.testingEquip(2,eq("old","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=*x.pendingCardSelection();x.testingRemoveEquipment(2,EquipmentSlot::OffensiveHorse);ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"old"}}).accepted,"removed mount rejected");ok(x.pendingCardSelection()&&x.kirinBowContext(),"removed request safe");}
void kirinBowRejectsReplacedMountId(){auto x=g();x.testingEquip(2,eq("old","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=*x.pendingCardSelection();x.testingRemoveEquipment(2,EquipmentSlot::OffensiveHorse);x.testingEquip(2,eq("new","大宛",EquipmentSlot::OffensiveHorse));ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"old"}}).accepted,"replaced old rejected");ok(x.player(2)->equipment(EquipmentSlot::OffensiveHorse)->id()=="new","new mount retained");}
void kirinBowTriggersAfterThunderSlash(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x,DamageNature::Thunder);auto s=*x.pendingCardSelection();ok(x.player(2)->hp()==3&&s.target==2&&s.selectableCards[0].cardId=="m","Thunder slash triggers Kirin");}
void kirinBowDoesNotTriggerOnNonSlashDamage(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));x.testingApplyDamage(Damage{1,2,1,DamageNature::Fire,false,false});ok(x.player(2)->hp()==3&&!x.pendingCardSelection()&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"non slash damage has no Kirin");}
void kirinBowDoesNotTriggerWhenDamageIsZero(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));x.testingApplyDamage(Damage{1,2,0,DamageNature::Normal,false,true});ok(x.player(2)->hp()==4&&!x.pendingCardSelection()&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"zero damage early return has no Kirin");}
void kirinBowDoesNotTriggerOnChainedPropagation(){auto x=g3();x.testingEquip(2,eq("m2","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(3,eq("m3","绝影",EquipmentSlot::DefensiveHorse));x.testingSetChained(2,true);x.testingSetChained(3,true);x.testingStartSlash(1,{2},1,DamageNature::Fire);auto r=*x.pendingResponse();ok(x.submitAction(RespondAction{2,r.requestId,std::nullopt}).accepted,"fire hit");auto s=*x.pendingCardSelection();ok(s.target==2&&x.player(3)->hp()==3,"only direct target gets request after chain");ok(x.submitAction(SelectCardsAction{1,s.requestId,{}}).accepted,"pass direct Kirin");ok(!x.pendingCardSelection()&&x.player(3)->equipment(EquipmentSlot::DefensiveHorse),"propagated target has no Kirin request");}
void kirinBowTimeoutCannotBeHandledTwice(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);ok(x.handleTimeout().accepted,"first timeout pass");const auto hp=x.player(2)->hp();x.handleTimeout();ok(x.player(2)->hp()==hp&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse)&&!x.pendingCardSelection()&&!x.kirinBowContext(),"second timeout cannot revive Kirin");}
void kirinBowMultiTargetOnlyTriggersForDamagedTarget(){auto x=g3();x.testingEquip(2,eq("a","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(3,eq("b","绝影",EquipmentSlot::DefensiveHorse));x.testingStartSlash(1,{2,3});auto r=*x.pendingResponse();x.submitAction(RespondAction{2,r.requestId,std::nullopt});auto s=*x.pendingCardSelection();ok(s.target==2,"A Kirin first");x.submitAction(SelectCardsAction{1,s.requestId,{}});r=*x.pendingResponse();x.players()[2]->addCard(std::make_shared<Card>("d","闪",CardType::Dodge,Suit::Heart,2));x.submitAction(RespondAction{3,r.requestId,"d"});ok(!x.pendingCardSelection()&&x.player(3)->equipment(EquipmentSlot::DefensiveHorse),"dodged B no Kirin");}
void kirinBowMultiTargetContinuesAfterFirstSelection(){auto x=g3();x.testingEquip(2,eq("a","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(3,eq("b","绝影",EquipmentSlot::DefensiveHorse));x.testingStartSlash(1,{2,3});auto r=*x.pendingResponse();x.submitAction(RespondAction{2,r.requestId,std::nullopt});auto a=*x.pendingCardSelection();x.submitAction(SelectCardsAction{1,a.requestId,{}});r=*x.pendingResponse();x.submitAction(RespondAction{3,r.requestId,std::nullopt});auto b=*x.pendingCardSelection();ok(a.target==2&&b.target==3&&a.requestId!=b.requestId&&b.selectableCards[0].cardId=="b","Kirin continues per target");}
void kirinBowDoesNotTriggerAfterUnequip(){auto x=g();x.testingRemoveEquipment(1,EquipmentSlot::Weapon);x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);ok(!x.pendingCardSelection(),"unequipped no Kirin");}
void kirinBowDoesNotTriggerAfterReplacement(){auto x=g();x.testingEquip(1,eq("new","青釭剑",EquipmentSlot::Weapon));x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);ok(!x.pendingCardSelection()&&x.player(1)->equipment(EquipmentSlot::Weapon)->id()=="new","replacement no Kirin");}
void kirinBowPendingRequestInvalidatesWhenWeaponIsLost(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=*x.pendingCardSelection();x.testingRemoveEquipment(1,EquipmentSlot::Weapon);ok(!x.submitAction(SelectCardsAction{1,s.requestId,{"m"}}).accepted&&!x.kirinBowContext()&&x.player(2)->equipment(EquipmentSlot::OffensiveHorse),"lost bow invalidates request");}
void kirinBowClearsWhenAttackerDies(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=*x.pendingCardSelection();x.testingKillPlayer(1);ok(!x.pendingCardSelection()&&!x.kirinBowContext()&&!x.submitAction(SelectCardsAction{1,s.requestId,{"m"}}).accepted,"attacker death clears");}
void kirinBowClearsWhenTargetDies(){auto x=g3();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit3(x);auto s=*x.pendingCardSelection();x.testingKillPlayer(2);ok(!x.pendingCardSelection()&&!x.kirinBowContext()&&!x.submitAction(SelectCardsAction{1,s.requestId,{"m"}}).accepted,"target death clears");}
void kirinBowClearsOnGameOver(){auto x=g();x.testingEquip(2,eq("m","赤兔",EquipmentSlot::OffensiveHorse));hit(x);auto s=*x.pendingCardSelection();x.testingKillPlayer(2);ok(x.gameOver()&&!x.pendingCardSelection()&&!x.kirinBowContext()&&!x.submitAction(SelectCardsAction{1,s.requestId,{"m"}}).accepted,"game over clears");}
void kirinBowContextDoesNotLeakToNextSlash(){auto x=g3();x.testingEquip(2,eq("a","赤兔",EquipmentSlot::OffensiveHorse));x.testingEquip(3,eq("b","绝影",EquipmentSlot::DefensiveHorse));hit3(x);auto a=*x.pendingCardSelection();x.submitAction(SelectCardsAction{1,a.requestId,{}});x.testingStartSlash(1,{3});auto r=*x.pendingResponse();x.submitAction(RespondAction{3,r.requestId,std::nullopt});auto b=*x.pendingCardSelection();ok(a.requestId!=b.requestId&&b.target==3&&b.selectableCards[0].cardId=="b","next slash fresh context");}
} int main(){test();kirinBowDoesNotTriggerWhenSlashIsDodged();kirinBowDoesNotTriggerWhenSlashIsPreventedByVine();kirinBowOffersBothMountsOnly();kirinBowRejectsWeaponCandidate();kirinBowRejectsStaleRequest();kirinBowRejectsNonActor();kirinBowRejectsArmorCandidate();kirinBowRejectsUnknownCandidate();kirinBowRejectsOtherPlayersMount();kirinBowRejectsCandidateRemovedAfterRequest();kirinBowRejectsReplacedMountId();kirinBowTriggersAfterThunderSlash();kirinBowDoesNotTriggerOnNonSlashDamage();kirinBowDoesNotTriggerWhenDamageIsZero();kirinBowDoesNotTriggerOnChainedPropagation();kirinBowTimeoutCannotBeHandledTwice();kirinBowMultiTargetOnlyTriggersForDamagedTarget();kirinBowMultiTargetContinuesAfterFirstSelection();kirinBowDoesNotTriggerAfterUnequip();kirinBowDoesNotTriggerAfterReplacement();kirinBowPendingRequestInvalidatesWhenWeaponIsLost();kirinBowClearsWhenAttackerDies();kirinBowClearsWhenTargetDies();kirinBowClearsOnGameOver();kirinBowContextDoesNotLeakToNextSlash();std::cout<<"BasicSanguoshaKirinBowTests PASS\n";}
